// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.mandii.newbackend.protos;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prototest.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string gender = 1;</code>
     */
    boolean hasGender();
    /**
     * <code>optional string gender = 1;</code>
     */
    java.lang.String getGender();
    /**
     * <code>optional string gender = 1;</code>
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>optional string occupation = 2;</code>
     */
    boolean hasOccupation();
    /**
     * <code>optional string occupation = 2;</code>
     */
    java.lang.String getOccupation();
    /**
     * <code>optional string occupation = 2;</code>
     */
    com.google.protobuf.ByteString
        getOccupationBytes();

    /**
     * <code>optional string first = 3;</code>
     */
    boolean hasFirst();
    /**
     * <code>optional string first = 3;</code>
     */
    java.lang.String getFirst();
    /**
     * <code>optional string first = 3;</code>
     */
    com.google.protobuf.ByteString
        getFirstBytes();

    /**
     * <code>optional string last = 4;</code>
     */
    boolean hasLast();
    /**
     * <code>optional string last = 4;</code>
     */
    java.lang.String getLast();
    /**
     * <code>optional string last = 4;</code>
     */
    com.google.protobuf.ByteString
        getLastBytes();
  }
  /**
   * Protobuf type {@code prototest.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:prototest.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              gender_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              occupation_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              first_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              last_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mandii.newbackend.protos.PersonProtos.Person.class, com.mandii.newbackend.protos.PersonProtos.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int GENDER_FIELD_NUMBER = 1;
    private java.lang.Object gender_;
    /**
     * <code>optional string gender = 1;</code>
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string gender = 1;</code>
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OCCUPATION_FIELD_NUMBER = 2;
    private java.lang.Object occupation_;
    /**
     * <code>optional string occupation = 2;</code>
     */
    public boolean hasOccupation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string occupation = 2;</code>
     */
    public java.lang.String getOccupation() {
      java.lang.Object ref = occupation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          occupation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string occupation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOccupationBytes() {
      java.lang.Object ref = occupation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        occupation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRST_FIELD_NUMBER = 3;
    private java.lang.Object first_;
    /**
     * <code>optional string first = 3;</code>
     */
    public boolean hasFirst() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string first = 3;</code>
     */
    public java.lang.String getFirst() {
      java.lang.Object ref = first_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          first_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string first = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFirstBytes() {
      java.lang.Object ref = first_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        first_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FIELD_NUMBER = 4;
    private java.lang.Object last_;
    /**
     * <code>optional string last = 4;</code>
     */
    public boolean hasLast() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string last = 4;</code>
     */
    public java.lang.String getLast() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          last_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastBytes() {
      java.lang.Object ref = last_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        last_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      gender_ = "";
      occupation_ = "";
      first_ = "";
      last_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOccupationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFirstBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLastBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOccupationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFirstBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLastBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mandii.newbackend.protos.PersonProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prototest.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prototest.Person)
        com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mandii.newbackend.protos.PersonProtos.Person.class, com.mandii.newbackend.protos.PersonProtos.Person.Builder.class);
      }

      // Construct using com.mandii.newbackend.protos.PersonProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        occupation_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        first_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        last_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_Person_descriptor;
      }

      public com.mandii.newbackend.protos.PersonProtos.Person getDefaultInstanceForType() {
        return com.mandii.newbackend.protos.PersonProtos.Person.getDefaultInstance();
      }

      public com.mandii.newbackend.protos.PersonProtos.Person build() {
        com.mandii.newbackend.protos.PersonProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mandii.newbackend.protos.PersonProtos.Person buildPartial() {
        com.mandii.newbackend.protos.PersonProtos.Person result = new com.mandii.newbackend.protos.PersonProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gender_ = gender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.occupation_ = occupation_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.first_ = first_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.last_ = last_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mandii.newbackend.protos.PersonProtos.Person) {
          return mergeFrom((com.mandii.newbackend.protos.PersonProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mandii.newbackend.protos.PersonProtos.Person other) {
        if (other == com.mandii.newbackend.protos.PersonProtos.Person.getDefaultInstance()) return this;
        if (other.hasGender()) {
          bitField0_ |= 0x00000001;
          gender_ = other.gender_;
          onChanged();
        }
        if (other.hasOccupation()) {
          bitField0_ |= 0x00000002;
          occupation_ = other.occupation_;
          onChanged();
        }
        if (other.hasFirst()) {
          bitField0_ |= 0x00000004;
          first_ = other.first_;
          onChanged();
        }
        if (other.hasLast()) {
          bitField0_ |= 0x00000008;
          last_ = other.last_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mandii.newbackend.protos.PersonProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mandii.newbackend.protos.PersonProtos.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object gender_ = "";
      /**
       * <code>optional string gender = 1;</code>
       */
      public boolean hasGender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string gender = 1;</code>
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gender = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gender = 1;</code>
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 1;</code>
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gender = 1;</code>
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        gender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object occupation_ = "";
      /**
       * <code>optional string occupation = 2;</code>
       */
      public boolean hasOccupation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string occupation = 2;</code>
       */
      public java.lang.String getOccupation() {
        java.lang.Object ref = occupation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            occupation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string occupation = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOccupationBytes() {
        java.lang.Object ref = occupation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          occupation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string occupation = 2;</code>
       */
      public Builder setOccupation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        occupation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string occupation = 2;</code>
       */
      public Builder clearOccupation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        occupation_ = getDefaultInstance().getOccupation();
        onChanged();
        return this;
      }
      /**
       * <code>optional string occupation = 2;</code>
       */
      public Builder setOccupationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        occupation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object first_ = "";
      /**
       * <code>optional string first = 3;</code>
       */
      public boolean hasFirst() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string first = 3;</code>
       */
      public java.lang.String getFirst() {
        java.lang.Object ref = first_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            first_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFirstBytes() {
        java.lang.Object ref = first_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          first_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first = 3;</code>
       */
      public Builder setFirst(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        first_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first = 3;</code>
       */
      public Builder clearFirst() {
        bitField0_ = (bitField0_ & ~0x00000004);
        first_ = getDefaultInstance().getFirst();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first = 3;</code>
       */
      public Builder setFirstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        first_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object last_ = "";
      /**
       * <code>optional string last = 4;</code>
       */
      public boolean hasLast() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string last = 4;</code>
       */
      public java.lang.String getLast() {
        java.lang.Object ref = last_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            last_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLastBytes() {
        java.lang.Object ref = last_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          last_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last = 4;</code>
       */
      public Builder setLast(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        last_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last = 4;</code>
       */
      public Builder clearLast() {
        bitField0_ = (bitField0_ & ~0x00000008);
        last_ = getDefaultInstance().getLast();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last = 4;</code>
       */
      public Builder setLastBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        last_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:prototest.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:prototest.Person)
  }

  public interface PersonListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prototest.PersonList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    java.util.List<com.mandii.newbackend.protos.PersonProtos.Person> 
        getPersonList();
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    com.mandii.newbackend.protos.PersonProtos.Person getPerson(int index);
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    java.util.List<? extends com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code prototest.PersonList}
   */
  public static final class PersonList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:prototest.PersonList)
      PersonListOrBuilder {
    // Use PersonList.newBuilder() to construct.
    private PersonList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonList defaultInstance;
    public static PersonList getDefaultInstance() {
      return defaultInstance;
    }

    public PersonList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<com.mandii.newbackend.protos.PersonProtos.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(com.mandii.newbackend.protos.PersonProtos.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_PersonList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_PersonList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mandii.newbackend.protos.PersonProtos.PersonList.class, com.mandii.newbackend.protos.PersonProtos.PersonList.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonList> PARSER =
        new com.google.protobuf.AbstractParser<PersonList>() {
      public PersonList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonList> getParserForType() {
      return PARSER;
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<com.mandii.newbackend.protos.PersonProtos.Person> person_;
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    public java.util.List<com.mandii.newbackend.protos.PersonProtos.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    public java.util.List<? extends com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    public com.mandii.newbackend.protos.PersonProtos.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .prototest.Person person = 1;</code>
     */
    public com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mandii.newbackend.protos.PersonProtos.PersonList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mandii.newbackend.protos.PersonProtos.PersonList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prototest.PersonList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prototest.PersonList)
        com.mandii.newbackend.protos.PersonProtos.PersonListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_PersonList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_PersonList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mandii.newbackend.protos.PersonProtos.PersonList.class, com.mandii.newbackend.protos.PersonProtos.PersonList.Builder.class);
      }

      // Construct using com.mandii.newbackend.protos.PersonProtos.PersonList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mandii.newbackend.protos.PersonProtos.internal_static_prototest_PersonList_descriptor;
      }

      public com.mandii.newbackend.protos.PersonProtos.PersonList getDefaultInstanceForType() {
        return com.mandii.newbackend.protos.PersonProtos.PersonList.getDefaultInstance();
      }

      public com.mandii.newbackend.protos.PersonProtos.PersonList build() {
        com.mandii.newbackend.protos.PersonProtos.PersonList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mandii.newbackend.protos.PersonProtos.PersonList buildPartial() {
        com.mandii.newbackend.protos.PersonProtos.PersonList result = new com.mandii.newbackend.protos.PersonProtos.PersonList(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mandii.newbackend.protos.PersonProtos.PersonList) {
          return mergeFrom((com.mandii.newbackend.protos.PersonProtos.PersonList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mandii.newbackend.protos.PersonProtos.PersonList other) {
        if (other == com.mandii.newbackend.protos.PersonProtos.PersonList.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mandii.newbackend.protos.PersonProtos.PersonList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mandii.newbackend.protos.PersonProtos.PersonList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mandii.newbackend.protos.PersonProtos.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<com.mandii.newbackend.protos.PersonProtos.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.mandii.newbackend.protos.PersonProtos.Person, com.mandii.newbackend.protos.PersonProtos.Person.Builder, com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public java.util.List<com.mandii.newbackend.protos.PersonProtos.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public com.mandii.newbackend.protos.PersonProtos.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.mandii.newbackend.protos.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.mandii.newbackend.protos.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder addPerson(com.mandii.newbackend.protos.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.mandii.newbackend.protos.PersonProtos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder addPerson(
          com.mandii.newbackend.protos.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.mandii.newbackend.protos.PersonProtos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.mandii.newbackend.protos.PersonProtos.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public com.mandii.newbackend.protos.PersonProtos.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public java.util.List<? extends com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public com.mandii.newbackend.protos.PersonProtos.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            com.mandii.newbackend.protos.PersonProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public com.mandii.newbackend.protos.PersonProtos.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, com.mandii.newbackend.protos.PersonProtos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .prototest.Person person = 1;</code>
       */
      public java.util.List<com.mandii.newbackend.protos.PersonProtos.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mandii.newbackend.protos.PersonProtos.Person, com.mandii.newbackend.protos.PersonProtos.Person.Builder, com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mandii.newbackend.protos.PersonProtos.Person, com.mandii.newbackend.protos.PersonProtos.Person.Builder, com.mandii.newbackend.protos.PersonProtos.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:prototest.PersonList)
    }

    static {
      defaultInstance = new PersonList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:prototest.PersonList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_PersonList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_PersonList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\tprototest\"I\n\006Person\022\016\n\006g" +
      "ender\030\001 \001(\t\022\022\n\noccupation\030\002 \001(\t\022\r\n\005first" +
      "\030\003 \001(\t\022\014\n\004last\030\004 \001(\t\"/\n\nPersonList\022!\n\006pe" +
      "rson\030\001 \003(\0132\021.prototest.PersonB,\n\034com.man" +
      "dii.newbackend.protosB\014PersonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_prototest_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prototest_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_prototest_Person_descriptor,
        new java.lang.String[] { "Gender", "Occupation", "First", "Last", });
    internal_static_prototest_PersonList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_prototest_PersonList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_prototest_PersonList_descriptor,
        new java.lang.String[] { "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
